# Form processor mapping configuration sample
# input_columns: canonical column -> possible source headers (Chinese/English)
input_columns:
  amount: ["金额", "应收金额", "Amount"]
  currency: ["币种", "Currency"]
  date: ["日期", "Date"]
  project: ["项目名称", "Project", "Description"]
  description: ["备注", "Remark"]

# computed: additional constant fields injected after mapping
computed:
  base_currency: "CNY"
  exchange_rate_source: "MockProvider"  # TODO: replace when integrating real fees_fetcher

# validations: required columns and numeric rules
validations:
  required: ["amount", "currency", "date", "project"]
  non_negative: ["amount"]
  round:
    amount: 2
    base_amount: 2

# thresholds: behaviour that may require human confirmation
thresholds:
  confirm_over_amount_cny: 20000
